version: "3"

services:
  redis:
    image: redis:7-bullseye
    restart: always
    volumes:
      - ./_data:/data
      - ./_data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    networks:
      - red
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.redis.loadbalancer.server.port=6379"
      - "traefik.http.routers.redis.rule=Host(`redis.authme.localhost`)"
      - "traefik.docker.network=red"

networks:
    red:
      external: true
      driver: bridge