global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

  consulCatalog:
    refreshInterval: 10s
    serviceName: "traefik"
    endpoint:
      address: "consul:8500"
      scheme: "http"
      tls:
        insecureSkipVerify: true
    exposedByDefault: true
    connectAware: true
    watch: true
    defaultRule: "Host(`{{ normalize .Name }}.authme.localhost`)"

log:
  level: DEBUG
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

  redis:
    address: ":6379"

  mysql:
    address: ":3306"
