global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

middlewares:
  latency-check:
    circuitbreaker:
      expression: LatencyAtQuantileMS(50.0) > 100
      notifiers:
        mail:
          delay: 1m
          emails:
            - admin@example.com

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
