#obtenemos la imagen de base
FROM authme-base:1.0.0

ENV REDIS_PASSWORD=${REDIS_PASSWORD}

USER flaskapp
RUN mkdir app
#copia la carpeta del proyecto a la imagen
COPY ./main ./main

COPY ./app.py .

ADD requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gevent gunicorn==20.1.0

#puerto por el que escucha la imagen
EXPOSE 5000

#HEALTHCHECK --interval=10s --timeout=10s --start-period=55s
#CMD curl -f --retry 10 --max-time 15 --retry-delay 10 --retry-max-time 60 "http://localhost:5000/api/v1/health" || exit 1

#ejecuta la aplicación
#CMD ["gunicorn", "--workers", "1", "--log-level", "INFO", "--bind", "0.0.0.0:5000", "app:create_app()"]
CMD [ "python", "./app.py" ]