version: "3"

services:
  redis:
    image: redis:7-bullseye
    restart: always
    volumes:
      - ~/dockers/redis/_data:/data
      - ~/dockers/redis/_data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - red

networks:
    red:
      external: true
      driver: bridge