http:
  routers:
    ms-otp:
      rule: "Host(`ms-otp.authme.localhost`)"
      service: "ms-otp"
      middlewares:
        - ms-otp-circuitbreaker
      tls:
        certResolver: "myresolver"

  middlewares:
    ms-otp-circuitbreaker:
      circuitbreaker:
        expression: LatencyAtQuantileMS(50.0) > 100

  services:
    ms-otp:
      loadBalancer:
        servers:
          - url: "http://ms-otp:5000"
