@startuml
actor User
actor App
participant "Sistema de Autenticación" as Auth
participant "Servicio de Correo Electrónico" as MailSender

User -> App: Introduce Credenciales
App -> Auth: Envia Credenciales
Auth -> Auth: Verifica Credenciales
Auth -> MailSender: Genera Código de Verificación
App -> User: Solicita Código de Verificación
MailSender -> User: Envía Código de Verificación
User -> App: Ingresa Código de Verificación
App -> Auth: Envia Código de Verificación
Auth -> Auth: Verifica Código de Verificación
Auth -> App: Autenticación Exitosa
@enduml