version: '3'

services:
  traefik:
    image: traefik:v2.9.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.email=youremail@example.com"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./_config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./_config/config.yml:/etc/traefik/config.yml:ro
      - ./_certs:/etc/certs:ro
    networks:
      - red
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.authme.localhost`)"
      - "traefik.docker.network=red"
      

networks:
  red:
    external: true