version: '3.3'
services:
    mysql:
        container_name: mysql-servidor
        image: mysql:8.0-debian

        command: --default-authentication-plugin=mysql_native_password
        networks:
            - red
        ports:
            - "3307:3306"
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./_data:/var/lib/mysql
        restart: always
        labels:
          - "traefik.enable=true"
          - "traefik.tcp.routers.mysql.entrypoints=mysql"
          - "traefik.http.routers.mysql.rule=Host(`mysql.authme.localhost`)"
          - "traefik.tcp.services.mysql.loadbalancer.server.port=3306" #no escalar
          - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
          - "traefik.docker.network=red"
networks:
    red:
        external: true