version: '3.3'
services:
    mysql:
        container_name: mysql-servidor
        image: mysql:8.0-debian

        command: --default-authentication-plugin=mysql_native_password
        networks:
            - red
        ports:
            - "3307:3306"
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            #- MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./_data:/var/lib/mysql
        restart: always
networks:
    red:
        external: true